# Generated by Django 5.1.1 on 2024-10-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
